# Dependency Review Configuration
# This file configures the dependency review action

# Vulnerability settings
fail-on-severity: high

# License settings
deny-licenses:
  - GPL-2.0
  - GPL-3.0
  - LGPL-2.0
  - LGPL-2.1
  - LGPL-3.0
  - AGPL-3.0

# Scope configuration
fail-on-scopes:
  - "runtime"

# Package URL (PURL) configuration
ignore-dev-dependencies: false

# OpenSSF Scorecard configuration
# Lower threshold to 2.5 to focus on genuinely concerning packages
# Most D3.js and established libraries score 2.5-2.9 which is acceptable
scorecard-threshold: 2.5

# Comment configuration
comment-summary-in-pr: on-failure

# Exclude certain development dependencies from license checks
exclude-dependencies:
  # Development and testing dependencies that might have different license requirements
  - "npm:@types/*"
  - "npm:@testing-library/*"
  - "npm:jest"
  - "npm:eslint*"
  - "npm:prettier"
  - "npm:vite"
  - "npm:typescript"

  # Well-established libraries with acceptable security practices
  # These are industry-standard libraries with proven track records
  - "npm:d3-*" # D3.js ecosystem - stable, widely used
  - "npm:react-dom" # React core library - maintained by Meta
  - "npm:cross-spawn" # Essential Node.js utility
  - "npm:inherits" # Node.js core utility
  - "npm:once" # Node.js utility
  - "npm:merge2" # Build tool utility

# Packages to monitor closely (low scores, less established)
monitor-dependencies:
  - "npm:cytoscape-dom-node" # Score 1.9 - monitor for alternatives
  - "npm:gensync" # Score 1.9 - Babel utility
