# Dependency Review Configuration
# This file configures the dependency review action to avoid PURL parsing errors

# Only use allow-licenses to avoid conflicts
allow-licenses:
  - MIT
  - Apache-2.0
  - BSD-2-Clause
  - BSD-3-Clause
  - ISC
  - MPL-2.0

# Vulnerability settings
fail-on-severity: high

# Package URL (PURL) configuration
ignore-dev-dependencies: true