# Dependency Review Configuration
# This file configures the dependency review action to avoid PURL parsing errors

# Allow specific license types
allow-licenses:
  - MIT
  - Apache-2.0
  - BSD-2-Clause
  - BSD-3-Clause
  - ISC
  - MPL-2.0

# Deny GPL licenses
deny-licenses:
  - GPL-2.0
  - GPL-3.0
  - LGPL-2.0
  - LGPL-2.1
  - LGPL-3.0

# Vulnerability settings
fail-on-severity: high

# Package URL (PURL) configuration
ignore-dev-dependencies: true