name: 📚 Documentation Issue
description: Report issues with documentation or request documentation improvements
title: "[DOCS] "
labels: ["documentation", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve our documentation! Clear documentation is essential for a great developer experience.

  - type: dropdown
    id: type
    attributes:
      label: Documentation Issue Type
      description: What type of documentation issue is this?
      options:
        - Missing documentation
        - Incorrect/outdated documentation
        - Unclear/confusing documentation
        - Broken links
        - Typos/grammar issues
        - Code examples not working
        - Missing API reference
        - Tutorial/guide request
        - Other
    validations:
      required: true

  - type: textarea
    id: location
    attributes:
      label: Documentation Location
      description: Where is the documentation issue located?
      placeholder: |
        - File: README.md, docs/api.md, etc.
        - URL: https://github.com/LederWorks/siros/...
        - Section: Installation, Configuration, API Reference, etc.
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Issue Description
      description: Describe the documentation issue in detail
      placeholder: What exactly is wrong or missing?
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Documentation
      description: What should the documentation say or include?
      placeholder: Describe what the correct/improved documentation should contain

  - type: dropdown
    id: audience
    attributes:
      label: Target Audience
      description: Who is the primary audience for this documentation?
      options:
        - New users/beginners
        - Developers integrating Siros
        - System administrators
        - Contributors/developers
        - All users
        - Other

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is fixing this documentation issue?
      options:
        - Low - Minor improvement
        - Medium - Helpful clarification
        - High - Important for user experience
        - Critical - Blocking user adoption

  - type: textarea
    id: suggestions
    attributes:
      label: Suggested Improvements
      description: Do you have specific suggestions for how to improve this documentation?
      placeholder: |
        - Add code examples
        - Include screenshots
        - Add troubleshooting section
        - Link to related documentation
        - etc.

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be willing to help improve this documentation?
      options:
        - label: I would like to write/update this documentation
        - label: I can provide technical review
        - label: I can provide examples or screenshots

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, links, or examples that would help improve the documentation